import { GraphNode, GraphEdge, TranscriptEntry, Project, Challenge, ReportData } from '@/types';

export const mockNodes: GraphNode[] = [
  {
    id: '1',
    type: 'idea',
    title: 'AI Matching Algorithm',
    summary: 'Match students by complementary skills',
    position: { x: 400, y: 200 },
    isActive: true,
    createdAt: Date.now() - 86400000,
    data: { suggestedBy: 'Sarah Chen' },
  },
  {
    id: '2',
    type: 'idea',
    title: 'Neural Graph Visualization',
    summary: 'React Flow with custom neuron nodes',
    position: { x: 650, y: 100 },
    isActive: true,
    createdAt: Date.now() - 72000000,
    data: { suggestedBy: 'Marcus Rivera' },
  },
  {
    id: '3',
    type: 'action',
    title: 'Implement Realtime Sync',
    summary: 'WebSocket + CRDT for collaboration',
    position: { x: 200, y: 350 },
    isActive: false,
    createdAt: Date.now() - 50000000,
    data: { suggestedBy: 'Aisha Patel' },
  },
  {
    id: '4',
    type: 'risk',
    title: 'Data Privacy Concerns',
    summary: 'Student recordings need consent',
    position: { x: 700, y: 350 },
    isActive: false,
    createdAt: Date.now() - 40000000,
    data: { suggestedBy: 'Prof. Yamamoto' },
  },
  {
    id: '5',
    type: 'decision',
    title: 'Tech Stack: Next.js + Supabase',
    summary: 'Full-stack with realtime DB',
    position: { x: 300, y: 550 },
    isActive: false,
    createdAt: Date.now() - 30000000,
    data: { suggestedBy: 'Team Vote' },
  },
  {
    id: '6',
    type: 'idea',
    title: 'Cyan/Orange Glow Theme',
    summary: 'Neural network visual identity',
    position: { x: 550, y: 500 },
    isActive: false,
    createdAt: Date.now() - 20000000,
    data: { suggestedBy: 'Design Lead' },
  },
  {
    id: '7',
    type: 'action',
    title: 'Generate Session Reports',
    summary: 'PDF export with AI summaries',
    position: { x: 150, y: 150 },
    isActive: false,
    createdAt: Date.now() - 15000000,
    data: { suggestedBy: 'Emma Wilson' },
  },
  {
    id: '8',
    type: 'question',
    title: 'Gamification Features?',
    summary: 'Challenges, leaderboards, badges',
    position: { x: 800, y: 200 },
    isActive: false,
    createdAt: Date.now() - 10000000,
    data: { suggestedBy: 'Jake Thompson' },
  },
  {
    id: '9',
    type: 'idea',
    title: 'Dark Mode by Default',
    summary: 'Reduce eye strain for study sessions',
    position: { x: 500, y: 700 },
    isActive: false,
    createdAt: Date.now() - 5000000,
    data: { suggestedBy: 'UX Researcher' },
  },
  {
    id: '10',
    type: 'risk',
    title: 'Scope Creep Risk',
    summary: 'Keep MVP under 5 core features',
    position: { x: 900, y: 500 },
    isActive: false,
    createdAt: Date.now() - 1000000,
    data: { suggestedBy: 'Project Manager' },
  },
];

export const mockEdges: GraphEdge[] = [
  { id: 'e1-2', source: '1', target: '2', type: 'active' },
  { id: 'e1-3', source: '1', target: '3', type: 'active' },
  { id: 'e2-9', source: '2', target: '9', type: 'inactive' },
  { id: 'e3-7', source: '3', target: '7', type: 'inactive' },
  { id: 'e4-1', source: '4', target: '1', type: 'inactive' },
  { id: 'e5-6', source: '5', target: '6', type: 'inactive' },
  { id: 'e6-8', source: '6', target: '8', type: 'active' },
  { id: 'e7-5', source: '7', target: '5', type: 'inactive' },
  { id: 'e8-4', source: '8', target: '4', type: 'inactive' },
  { id: 'e10-3', source: '10', target: '3', type: 'inactive' },
  { id: 'e10-5', source: '10', target: '5', type: 'inactive' },
  { id: 'e2-6', source: '2', target: '6', type: 'inactive' },
];

export const mockTranscripts: TranscriptEntry[] = [
  {
    id: 't1',
    speaker: 'Sarah Chen',
    text: 'What if we could match students based on complementary learning styles?',
    timestamp: '10:23 AM',
    relatedNodeId: '1',
  },
  {
    id: 't2',
    speaker: 'Marcus Rivera',
    text: 'The visualization should feel like a living neural network - nodes connecting in real-time.',
    timestamp: '10:25 AM',
    relatedNodeId: '2',
  },
  {
    id: 't3',
    speaker: 'Aisha Patel',
    text: 'We need real-time sync so multiple students can collaborate on the same graph.',
    timestamp: '10:28 AM',
    relatedNodeId: '3',
  },
  {
    id: 't4',
    speaker: 'Prof. Yamamoto',
    text: 'Student data privacy is critical - we must obtain explicit consent before any recording.',
    timestamp: '10:30 AM',
    relatedNodeId: '4',
  },
  {
    id: 't5',
    speaker: 'Team',
    text: 'Decision: Next.js for frontend, Supabase for backend with realtime capabilities.',
    timestamp: '10:33 AM',
    relatedNodeId: '5',
  },
  {
    id: 't6',
    speaker: 'Design Lead',
    text: 'The visual identity should feel like biotech intelligence - cyan glows on violet.',
    timestamp: '10:35 AM',
    relatedNodeId: '6',
  },
  {
    id: 't7',
    speaker: 'Emma Wilson',
    text: 'After each session, we should generate a PDF report with AI-summarized insights.',
    timestamp: '10:38 AM',
    relatedNodeId: '7',
  },
  {
    id: 't8',
    speaker: 'Jake Thompson',
    text: 'Should we add gamification? Like challenges and leaderboards to boost engagement?',
    timestamp: '10:40 AM',
    relatedNodeId: '8',
  },
  {
    id: 't9',
    speaker: 'UX Researcher',
    text: 'Dark mode should be the default - students study at night and need eye comfort.',
    timestamp: '10:43 AM',
    relatedNodeId: '9',
  },
  {
    id: 't10',
    speaker: 'PM',
    text: 'We need to watch scope creep. Keep the MVP focused on core features only.',
    timestamp: '10:45 AM',
    relatedNodeId: '10',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    title: 'StudySync Platform',
    description: 'AI-powered study group matching with live idea mapping.',
    progress: 65,
    status: 'active',
    nodeCount: 10,
    lastActive: '2 hours ago',
    color: '#8b5cf6',
  },
  {
    id: 'p2',
    title: 'NeuroLearn Dashboard',
    description: 'Analytics dashboard for learning pattern visualization.',
    progress: 30,
    status: 'active',
    nodeCount: 6,
    lastActive: '1 day ago',
    color: '#3b82f6',
  },
  {
    id: 'p3',
    title: 'Campus Connect MVP',
    description: 'Initial campus networking platform prototype.',
    progress: 100,
    status: 'completed',
    nodeCount: 15,
    lastActive: '1 week ago',
    color: '#34d399',
  },
];

export const mockChallenges: Challenge[] = [
  {
    id: 'c1',
    title: 'Brainstorm Alternatives',
    description: 'Generate 5 alternative approaches to the core problem.',
    duration: 5,
    completed: false,
    type: 'brainstorm',
  },
  {
    id: 'c2',
    title: 'Challenge Assumptions',
    description: 'List all assumptions and find counter-examples.',
    duration: 7,
    completed: false,
    type: 'assumption',
  },
  {
    id: 'c3',
    title: 'Find Hidden Connections',
    description: 'Identify 3 unexpected relationships between nodes.',
    duration: 5,
    completed: true,
    type: 'connection',
  },
  {
    id: 'c4',
    title: 'Synthesize Solutions',
    description: 'Combine 3 ideas into one cohesive solution.',
    duration: 10,
    completed: false,
    type: 'synthesis',
  },
  {
    id: 'c5',
    title: 'Risk Assessment',
    description: 'Identify top 5 risks and mitigation strategies.',
    duration: 8,
    completed: false,
    type: 'risk',
  },
];

export const mockReport: ReportData = {
  sessionId: 'sess-2026-001',
  sessionTitle: 'StudySync Platform Brainstorm',
  generatedAt: new Date().toISOString(),
  totalNodes: 10,
  totalTranscripts: 10,
  keyDecisions: 2,
  actionItems: 2,
  risks: 2,
  questions: 1,
  ideas: 3,
  summary: 'The team agreed on a Next.js + Supabase stack for the StudySync platform. Key decisions include implementing AI matching algorithms, real-time collaboration with CRDTs, and a neural network-inspired visual identity. Privacy concerns were noted around student data recording.',
  nextSteps: [
    'Set up Supabase project with realtime capabilities',
    'Design wireframes for the neural graph visualization',
    'Draft privacy policy and consent flow',
    'Prototype AI matching algorithm with mock data',
    'Schedule follow-up session for gamification discussion',
  ],
};